name: 'Continuous Integration'

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest tests/model/test_model.py
          pytest tests/api/test_api.py
          pytest tests/stress/api_stress.py

